'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});

var _slicedToArray = (function () { function sliceIterator(arr, i) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i['return']) _i['return'](); } finally { if (_d) throw _e; } } return _arr; } return function (arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { return sliceIterator(arr, i); } else { throw new TypeError('Invalid attempt to destructure non-iterable instance'); } }; })();

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

var _muiMaterialStyles = require('@mui/material/styles');

var _muiMaterial = require('@mui/material');

// Create context
var AppContext = (0, _react.createContext)();

// Default theme
var getDesignTokens = function getDesignTokens(mode) {
  return {
    palette: _extends({
      mode: mode
    }, mode === 'light' ? {
      // Light mode
      primary: {
        main: '#1e3c72'
      },
      secondary: {
        main: '#2a5298'
      },
      background: {
        'default': '#f5f5f5',
        paper: '#ffffff'
      },
      text: {
        primary: '#212121',
        secondary: '#757575'
      }
    } : {
      // Dark mode
      primary: {
        main: '#64b5f6'
      },
      secondary: {
        main: '#bb86fc'
      },
      background: {
        'default': '#121212',
        paper: '#1d1d1d'
      },
      text: {
        primary: '#ffffff',
        secondary: '#b3b3b3'
      }
    })
  };
};

var AppProvider = function AppProvider(_ref) {
  var children = _ref.children;

  // Load preferences from localStorage

  var _useState = (0, _react.useState)(function () {
    var savedMode = localStorage.getItem('themeMode');
    return savedMode ? savedMode : 'light';
  });

  var _useState2 = _slicedToArray(_useState, 2);

  var mode = _useState2[0];
  var setMode = _useState2[1];

  var _useState3 = (0, _react.useState)(function () {
    var savedLanguage = localStorage.getItem('language');
    return savedLanguage ? savedLanguage : 'fr';
  });

  var _useState32 = _slicedToArray(_useState3, 2);

  var language = _useState32[0];
  var setLanguage = _useState32[1];

  // Save preferences to localStorage
  (0, _react.useEffect)(function () {
    localStorage.setItem('themeMode', mode);
  }, [mode]);

  (0, _react.useEffect)(function () {
    localStorage.setItem('language', language);
  }, [language]);

  // Toggle theme mode
  var toggleTheme = function toggleTheme() {
    setMode(function (prevMode) {
      return prevMode === 'light' ? 'dark' : 'light';
    });
  };

  // Change language
  var changeLanguage = function changeLanguage(newLanguage) {
    setLanguage(newLanguage);
  };

  // Current theme
  var theme = (0, _muiMaterialStyles.createTheme)(getDesignTokens(mode));

  // Translations
  var translations = {
    fr: {
      // French translations
      dashboard: 'Tableau de bord',
      leaderboard: 'Classement',
      pricing: 'Tarifs',
      admin: 'Admin',
      home: 'Accueil',
      login: 'Se connecter',
      register: 'S\'inscrire',
      logout: 'Se déconnecter',
      darkMode: 'Mode sombre',
      lightMode: 'Mode clair',
      language: 'Langue',
      french: 'Français',
      english: 'Anglais',
      arabic: 'Arabe',
      productVision: 'Notre Vision Produit',
      productVisionDescription: 'Une plateforme complète qui combine intelligence artificielle, analyse de marché et communauté de traders',
      advancedAIAssistance: 'Assistance IA Avancée',
      advancedAIAssistanceDesc: 'Notre IA analyse les marchés en temps réel pour vous fournir des signaux de trading précis et des analyses techniques approfondies.',
      preciseTradingSignals: 'Signaux de Trading Précis',
      latestFinancialNews: 'Dernières Nouvelles Financières',
      fedPauseHike: 'La Fed décide de suspendre la hausse des taux pour le moment',
      iamUpQuarterly: 'IAM affiche une progression de 5% au cours du dernier trimestre',
      cryptoRegulationNews: 'Nouvelle réglementation pour les cryptomonnaies en Europe',
      ago: 'auparavant',
      close: 'Fermer',
      goToDashboard: 'Aller au Dashboard',
      videos: 'Vidéos',
      courseContent: 'Contenu du Cours',
      learningMaterials: 'Matériel d\'apprentissage',
      courseProgress: 'Progression',
      progressOverview: 'Aperçu de la progression',
      courseProgressDescription: 'Complétez divers modules pour progresser dans le cours.',
      markAsComplete: 'Marquer comme terminé',
      congratulations: 'Félicitations !',
      courseCompletedSuccessfully: 'Vous avez terminé le cours avec succès !',
      courseCertificateInfo: 'Vous pouvez maintenant télécharger votre certificat de complétion.',
      downloadCertificate: 'Télécharger le certificat',
      courseNotFound: 'Cours non trouvé',
      download: 'Télécharger',
      hideCommunity: 'Masquer la Communauté',
      hideStrategies: 'Masquer les Stratégies',
      communityFeatures: 'Fonctionnalités de la Communauté',
      scalpingStrategy: 'Stratégie de Scalping',
      scalpingStrategyDesc: 'Stratégie à très court terme visant des profits minimes sur de nombreuses transactions',
      dayTradingStrategy: 'Stratégie de Day Trading',
      dayTradingStrategyDesc: 'Achat et vente d\'actions le même jour sans position overnight',
      swingTradingStrategy: 'Stratégie de Swing Trading',
      swingTradingStrategyDesc: 'Tenue de positions pendant plusieurs jours à plusieurs semaines',
      positionTradingStrategy: 'Stratégie de Position Trading',
      positionTradingStrategyDesc: 'Approche à long terme avec des positions tenues pendant des mois',
      entryRules: 'Règles d\'entrée',
      exitRules: 'Règles de sortie',
      scalpingEntryRules: '- RSI entre 30-70\\n- Volume élevé (>200k)\\n- Éloignement du prix moyen',
      scalpingExitRules: '- Stop loss à 0.1%\\n- Take profit à 0.3%\\n- Sortie si RSI dépasse 80 ou descend en dessous de 20',
      dayTradingEntryRules: '- Croisement de moyennes mobiles\\n- Breakout de canal de prix\\n- Nouvelles importantes',
      dayTradingExitRules: '- Stop loss à 2%\\n- Take profit à 5%\\n- Fermeture avant la fin de la journée',
      swingTradingEntryRules: '- Confirmation de tendance\\n- Niveaux de support/résistance\\n- Indicateurs techniques alignés',
      swingTradingExitRules: '- Stop loss à 5%\\n- Take profit à 15%\\n- Suivi de la tendance',
      positionTradingEntryRules: '- Analyse fondamentale solide\\n- Tendance à long terme\\n- Alignement macroéconomique',
      positionTradingExitRules: '- Stop loss à 10%\n- Take profit à 30%\n- Changement de tendance fondamentale',
      hideDiscussions: 'Masquer les Discussions',
      hideInsights: 'Masquer les Aperçus',
      tradingStrategies: 'Stratégies de Trading',
      euroUsdAnalysis: 'Analyse EUR/USD',
      euroUsdAnalysisDesc: 'Le couple EUR/USD semble former un modèle de continuation haussier à court terme.',
      goldTrendPrediction: 'Prédiction tendance Or',
      goldTrendPredictionDesc: 'L\'or devrait continuer à grimper en raison des tensions géopolitiques croissantes.',
      oilMarketUpdate: 'Mise à jour marché Pétrole',
      oilMarketUpdateDesc: 'Les stocks de pétrole brut ont baissé cette semaine, soutenant les prix.',
      techStockWatch: 'Surveillance actions Tech',
      techStockWatchDesc: 'Les actions tech montrent des signes de reprise après la correction récente.',
      postedBy: 'Posté par',
      userTraderPro: 'TraderPro',
      userMarketGuru: 'MarketGuru',
      userOilExpert: 'OilExpert',
      userTechTrader: 'TechTrader',
      threeHoursAgo: 'il y a 3 heures',
      fourHoursAgo: 'il y a 4 heures',
      sixHoursAgo: 'il y a 6 heures',
      eightHoursAgo: 'il y a 8 heures',
      weeklyMarketOutlook: 'Vue hebdomadaire du marché',
      weeklyMarketOutlookDesc: 'Analyse approfondie des tendances dominantes et des opportunités à venir.',
      riskManagementTips: 'Conseils de gestion des risques',
      riskManagementTipsDesc: 'Meilleures pratiques pour protéger votre capital dans des marchés volatils.',
      forexFundamentals: 'Fondamentaux Forex',
      forexFundamentalsDesc: 'Compréhension des facteurs économiques qui influencent les paires de devises.',
      stockValuationGuide: 'Guide d\'évaluation boursière',
      stockValuationGuideDesc: 'Méthodes pour évaluer si une action est surévaluée ou sous-évaluée.',
      by: 'Par',
      expertAnalyst: 'ExpertAnalyst',
      expertRiskManager: 'ExpertRiskManager',
      expertForexTrader: 'ExpertForexTrader',
      expertValueInvestor: 'ExpertValueInvestor',
      updatedToday: 'mis à jour aujourd\'hui',
      updatedYesterday: 'mis à jour hier',
      updatedTwoDaysAgo: 'mis à jour avant-hier',
      updatedThreeDaysAgo: 'mis à jour il y a 3 jours',
      viewDiscussion: 'Voir Discussion',
      readMore: 'Lire la suite',
      tradingStrategiesDesc: 'Partagez et découvrez des stratégies de trading éprouvées',
      marketDiscussions: 'Discussions sur le Marché',
      marketDiscussionsDesc: 'Discutez des tendances du marché avec d\'autres traders',
      expertInsights: 'Aperçus d\'Experts',
      expertInsightsDesc: 'Accédez aux analyses des experts en trading',
      activeDiscussions: 'Discussions Actives',
      discussionTopic1: 'Stratégie de day trading pour les débutants',
      discussionTopic1Desc: 'Parcourez les meilleures pratiques pour commencer à trader',
      discussionTopic2: 'Analyse technique de l\'EUR/USD',
      discussionTopic2Desc: 'Discussion sur les niveaux clés de support et de résistance',
      discussionTopic3: 'Gestion des risques dans le trading',
      discussionTopic3Desc: 'Comment protéger votre capital avec des stops appropriés',
      joinCommunity: 'Rejoindre la Communauté',
      asset: 'Actif',
      aiBuySignal: 'RSI divergence haussière',
      aiBuyTechnicalAnalysis: 'L\'indice de Force Relative montre un modèle de divergence haussière où le prix fait des plus bas tandis que le RSI fait des plus hauts, indiquant un potentiel retournement à la hausse.',
      aiSellSignal: 'Conditions de surachats',
      aiSellTechnicalAnalysis: 'Le prix se négocie au-dessus de la bande supérieure de Bollinger avec un RSI supérieur à 70, indiquant des conditions de surachat et un potentiel de correction.',
      aiBuySignal2: 'Maintien du niveau de support',
      aiBuyTechnicalAnalysis2: 'Le prix a trouvé un solide support au niveau de 78.00 avec un volume croissant sur le rebond, suggérant un accumulation institutionnelle.',
      newsHub: 'Hub d\'Actualités',
      newsHubDesc: 'Restez informé des dernières nouvelles financières, des tendances du marché et des événements économiques en direct.',
      communityZone: 'Zone Communautaire',
      communityZoneDesc: 'Partagez vos stratégies, discutez avec d\'autres traders et collaborez dans notre communauté active de professionnels.',
      tradingMasterclass: 'MasterClass de Trading',
      tradingMasterclassDesc: 'Des formations exclusives dispensées par des traders professionnels pour améliorer vos compétences et votre rentabilité.',
      beginnerCourse: 'Formation Débutant',
      beginnerCourseDesc: 'Apprenez les bases du trading et de l\'analyse du marché',
      advancedCourse: 'Formation Avancée',
      advancedCourseDesc: 'Techniques de trading avancées et analyse technique approfondie',
      expertCourse: 'Formation Expert',
      expertCourseDesc: 'Analyse quantitative et gestion avancée du portefeuille',
      specializedCourse: 'Formation Spécialisée',
      specializedCourseDesc: 'Trading dans les marchés forex, options et cryptomonnaies',
      beginnerLevel: 'Débutant',
      intermediateLevel: 'Intermédiaire',
      advancedLevel: 'Avancé',
      expertLevel: 'Expert',
      courseDetails: 'Détails de la Formation',
      topicsCovered: 'Thèmes Abordés',
      enrollNow: 'S\'inscrire Maintenant',
      enrollSuccess: 'Inscription à la formation réussie!',
      hideMasterclass: 'Masquer la Formation',
      lessons: 'Leçons',
      availableCourses: 'Cours Disponibles',
      duration: 'Durée',
      level: 'Niveau',
      introToTrading: 'Introduction au Trading',
      chartPatterns: 'Modèles Graphiques',
      riskBasics: 'Bases de la Gestion des Risques',
      technicalAnalysis: 'Analyse Technique',
      algorithmicTrading: 'Trading Algorithmique',
      portfolioManagement: 'Gestion de Portefeuille',
      quantitativeAnalysis: 'Analyse Quantitative',
      riskManagement: 'Gestion des Risques',
      momentumTrading: 'Trading de Momentum',
      forexTrading: 'Trading Forex',
      optionsStrategy: 'Stratégie d\'Options',
      cryptoMarkets: 'Marchés Crypto',
      tradingChallenges: 'Challenges de Trading',
      tradingChallengesDesc: 'Relevez des défis de trading pour prouver vos compétences et gagner des fonds pour trader avec de l\'argent réel.',
      takeChallenge: 'Relever le Défi',
      learnMore: 'En savoir Plus',
      technicalAnalysisControls: 'Contrôles d\'Analyse Technique',
      indicatorType: 'Type d\'indicateur',
      period: 'Période',
      none: 'Aucun',
      simpleMovingAverage: 'Moyenne Mobile Simple',
      exponentialMovingAverage: 'Moyenne Mobile Exponentielle',
      movingAverageConvergenceDivergence: 'Convergence/Divergence Moyenne Mobile',
      stochasticOscillator: 'Oscillateur Stochastique',
      williamsR: '%R de Williams',
      smaExplanation: 'La moyenne mobile simple (SMA) lisse les données de prix en créant une moyenne constamment mise à jour sur une période spécifique, aidant à identifier la direction de la tendance et les niveaux potentiels de support/résistance.',
      emaExplanation: 'La moyenne mobile exponentielle (EMA) donne plus de poids aux prix récents, la rendant plus réactive aux nouvelles informations comparée à la SMA, utile pour identifier les changements de tendance plus rapidement.',
      rsiExplanation: 'L\'indice de force relative (RSI) mesure la vitesse et le changement des mouvements de prix, allant de 0 à 100. Les valeurs supérieures à 70 indiquent des conditions de surachat, tandis que les valeurs inférieures à 30 indiquent des conditions de survente.',
      bollingerExplanation: 'Les bandes de Bollinger consistent en une bande centrale SMA et deux bandes extérieures qui sont généralement à 2 écarts-types de la SMA. Elles aident à identifier les périodes de haute ou basse volatilité et les points potentiels de retournement.',
      macdExplanation: 'La convergence/divergence de moyenne mobile (MACD) montre la relation entre deux EMAs de différentes périodes. Elle comprend la ligne MACD, la ligne de signal et l\'histogramme, utile pour identifier les changements de tendance et les décalages de momentum.',
      stochasticExplanation: 'L\'oscillateur stochastique compare le prix de clôture d\'un titre à sa plage de prix sur une période donnée. Il varie de 0 à 100 et aide à identifier les conditions de surachat (au-dessus de 80) et de survente (en dessous de 20).',
      williamsRExplanation: 'Williams %R est un indicateur de momentum similaire à l\'oscillateur stochastique, mais inversé. Il varie de -100 à 0, où les valeurs au-dessus de -20 indiquent des conditions de surachat et celles en dessous de -80 indiquent des conditions de survente.',
      generalExplanation: 'Les indicateurs techniques aident les traders à prendre des décisions éclairées en analysant les mouvements de prix, les tendances et la sentiment du marché. Utilisez plusieurs indicateurs ensemble pour une meilleure précision.',
      showBollingerBands: 'Afficher Bandes de Bollinger',
      showRSI: 'Afficher RSI',
      showMACD: 'Afficher MACD',
      showStochastic: 'Afficher Stochastique',
      showWilliamsR: 'Afficher %R de Williams',
      price: 'Prix',

      readyToTransformTrading: 'Prêt à transformer votre trading ?',
      joinTradersAlreadyUsing: 'Rejoignez des milliers de traders qui utilisent déjà TradeSense AI',
      createFreeAccount: 'Créer un Compte Gratuit',
      getStartedNow: 'Commencer Maintenant',
      landingProductPlatform: 'La plateforme de prop trading intelligente pour les traders ambitieux',
      quickLinks: 'Liens Rapides',
      about: 'À propos',
      helpCenter: 'Centre d\'aide',
      documentation: 'Documentation',
      api: 'API',
      support: 'Support',
      allRightsReserved: 'Tous droits réservés.',
      tradingDashboard: 'Tableau de Bord de Trading',
      stockPerformance: 'Performance des Actions',
      challengeBalance: 'Solde de Challenge',
      selectedAsset: 'Actif Sélectionné',
      currentPrice: 'Prix Actuel',
      priceChart: 'Graphique de Prix',
      selectAsset: 'Sélectionnez un actif',
      buy: 'Acheter',
      sell: 'Vendre',
      hold: 'Hold',
      realTimeAISignals: 'Signaux IA en Temps Réel',
      reason: 'Raison',
      signalsGeneratedByAI: 'Les signaux sont générés par notre IA basée sur l\'analyse technique et les modèles prédictifs',
      signalDetails: 'Détails du signal',
      confidence: 'Confiance',
      timeFrame: 'Période',
      targetPrice: 'Prix cible',
      stopLoss: 'Stop Loss',
      indicatorsUsed: 'Indicateurs utilisés',
      goToTrainingCourses: 'Aller aux Cours de Formation',
      tradingStats: 'Statistiques de Trading',
      openPositions: 'Positions Ouvertes',
      profitLoss: 'Gains/Pertes',
      successRate: 'Taux de Réussite',
      volatility: 'Volatilité',
      medium: 'Moyenne',
      marketNews: 'Dernières Nouvelles du Marché',
      hoursAgo: 'il y a {hours} heures',
      purchaseSuccess: 'Achat de {asset} effectué avec succès!',
      purchaseError: 'Erreur lors de l\'achat',
      purchaseRetry: 'Erreur lors de l\'achat. Veuillez réessayer.',
      saleSuccess: 'Vente de {asset} effectuée avec succès!',
      saleError: 'Erreur lors de la vente',
      saleRetry: 'Erreur lors de la vente. Veuillez réessayer.',
      fetchPriceError: 'Erreur lors de la récupération du prix',
      traderLeaderboard: 'Classement des Traders',
      top10TradersByProfitPercent: 'Top 10 des meilleurs traders selon leur pourcentage de profit',
      rank: 'Rang',
      profitPercent: 'Profit (%)',
      totalProfitDollar: 'Profit Total ($)',
      transactions: 'Transactions',
      funded: 'Funded',
      active: 'Actif',
      failed: 'Échoué',
      rankingMethodology: 'Méthodologie de classement',
      rankingExplanation: 'Les traders sont classés selon leur pourcentage de profit net calculé comme suit: (Solde Final - Solde Initial) / Solde Initial × 100. Seuls les challenges terminés sont éligibles pour le classement.',
      fetchLeaderboardError: 'Erreur lors de la récupération des données du classement',
      adminPanel: 'Panneau d\'Administration',
      userManagement: 'Gestion des utilisateurs et de leurs statuts',
      userId: 'ID',
      username: 'Nom d\'utilisateur',
      email: 'Email',
      challengeId: 'Challenge ID',
      challengeStatus: 'Statut du Challenge',
      currentBalance: 'Solde Actuel',
      initialBalance: 'Solde Initial',
      actions: 'Actions',
      modify: 'Modifier',
      updateChallengeStatus: 'Modifier le Statut du Challenge',
      user: 'Utilisateur',
      update: 'Mettre à jour',
      loadingUsers: 'Chargement des utilisateurs...',
      fetchUsersError: 'Erreur lors du chargement des utilisateurs',
      updateStatusError: 'Erreur lors de la mise à jour du statut',
      noChallenge: 'Aucun',
      nA: 'N/A',
      chooseYourPlan: 'Choisissez votre Plan',
      accessAdvancedFeatures: 'Accédez à des fonctionnalités avancées pour optimiser votre trading',
      perMonth: 'par mois',
      popular: 'POPULAIRE',
      chooseStarter: 'Choisir Starter',
      choosePro: 'Choisir Pro',
      chooseElite: 'Choisir Elite',
      processingPayment: 'Traitement du paiement...',
      paymentSuccess: 'Paiement réussi!',
      payment: 'Paiement',
      paymentProcessing: 'Traitement de votre paiement...',
      pleaseWaitPaymentProcessing: 'Veuillez patienter pendant que nous traitons votre paiement de {price} {currency}.',
      paymentSuccessMessage: 'Merci pour votre paiement de {price} {currency}.<br />Votre abonnement {plan} est maintenant actif.',
      paymentInfo: 'Paiement de {price} {currency} pour le plan {plan}',
      cardNumber: 'Numéro de carte',
      expiryDate: 'Date d\'expiration',
      cvv: 'CVV',
      cardHolderName: 'Nom du titulaire',
      saveForFuturePayments: 'Enregistrer ces informations pour les prochains paiements',
      cancel: 'Annuler',
      payAmount: 'Payer {price} {currency}',
      whyChooseTradeSense: 'Pourquoi choisir TradeSense AI ?',
      advancedAI: 'Intelligence Artificielle Avancée',
      advancedAIExplanation: 'Nos algorithmes d\'IA analysent des millions de données en temps réel pour vous fournir les meilleurs signaux de trading.',
      completePlatform: 'Plateforme Complète',
      completePlatformExplanation: 'Tout-en-un : graphiques avancés, signaux IA, gestion de portefeuille, et communauté de traders professionnels.',
      localSupport: 'Support Local',
      localSupportExplanation: 'Service client disponible en français et arabe, avec une expertise du marché marocain et international.',
      starterFeatures: ['Accès aux graphiques de base', '5 signaux IA par jour', 'Support par email', '1 challenge de trading', 'Historique limité'],
      proFeatures: ['Tous les avantages Starter', 'Signaux IA illimités', 'Support prioritaire', '5 challenges de trading', 'Analyse technique avancée', 'Webinars mensuels'],
      eliteFeatures: ['Tous les avantages Pro', 'Accès anticipé aux nouvelles fonctionnalités', 'Session de coaching personnalisée', 'Accès à la communauté VIP', 'Signaux IA en temps réel', 'Analyses hebdomadaires exclusives', 'Support 24/7'],
      paymentFailure: 'Échec du paiement. Veuillez vérifier vos informations de carte.',
      tradeSenseAuth: 'TradeSense AI - Authentification',
      confirmPassword: 'Confirmer le mot de passe',
      passwordsDontMatch: 'Les mots de passe ne correspondent pas',
      registrationSuccess: 'Inscription réussie! Vous pouvez maintenant vous connecter.',
      registrationError: 'Erreur lors de l\'inscription',
      loginRequiredFields: 'Veuillez remplir tous les champs requis',
      loginSuccess: 'Connexion réussie!',
      loginError: 'Erreur lors de la connexion',
      networkError: 'Erreur réseau. Veuillez réessayer.',
      checkingConnection: 'Vérification de la connexion...',
      connectionTroubleShoot: 'Veuillez vous assurer que le serveur backend fonctionne sur le port 5000.',
      connectionTroubleshootSteps: 'Étapes de dépannage : Assurez-vous que le serveur backend est en cours d\'exécution sur le port 5000, vérifiez les paramètres du pare-feu et assurez-vous de la connectivité réseau.',
      requiredFields: 'Veuillez remplir tous les champs requis',
      confirmPurchase: 'Confirmer l\'achat',
      confirmPurchaseMessage: 'Êtes-vous sûr de vouloir acheter le challenge {plan}?'
    },
    // Add more translations as needed
    en: {
      // English translations
      dashboard: 'Dashboard',
      leaderboard: 'Leaderboard',
      pricing: 'Pricing',
      admin: 'Admin',
      home: 'Home',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      language: 'Language',
      french: 'French',
      english: 'English',
      arabic: 'Arabic',
      productVision: 'Our Product Vision',
      productVisionDescription: 'A complete platform that combines artificial intelligence, market analysis and trader community',
      advancedAIAssistance: 'Advanced AI Assistance',
      advancedAIAssistanceDesc: 'Our AI analyzes markets in real-time to provide you with accurate trading signals and in-depth technical analysis.',
      preciseTradingSignals: 'Precise Trading Signals',
      latestFinancialNews: 'Latest Financial News',
      fedPauseHike: 'Fed decides to pause rate hikes for now',
      iamUpQuarterly: 'IAM shows 5% progress in the last quarter',
      cryptoRegulationNews: 'New cryptocurrency regulation in Europe',
      ago: 'ago',
      close: 'Close',
      goToDashboard: 'Go to Dashboard',
      videos: 'Videos',
      courseContent: 'Course Content',
      learningMaterials: 'Learning Materials',
      courseProgress: 'Progress',
      progressOverview: 'Progress Overview',
      courseProgressDescription: 'Complete various modules to progress through the course.',
      markAsComplete: 'Mark Course as Complete',
      congratulations: 'Congratulations!',
      courseCompletedSuccessfully: 'You have successfully completed the course!',
      courseCertificateInfo: 'You can now download your certificate of completion.',
      downloadCertificate: 'Download Certificate',
      courseNotFound: 'Course not found',
      download: 'Download',
      hideCommunity: 'Hide Community',
      hideStrategies: 'Hide Strategies',
      communityFeatures: 'Community Features',
      scalpingStrategy: 'Scalping Strategy',
      scalpingStrategyDesc: 'Very short-term strategy aiming for tiny profits on many transactions',
      dayTradingStrategy: 'Day Trading Strategy',
      dayTradingStrategyDesc: 'Buying and selling stocks on the same day without overnight positions',
      swingTradingStrategy: 'Swing Trading Strategy',
      swingTradingStrategyDesc: 'Holding positions for several days to several weeks',
      positionTradingStrategy: 'Position Trading Strategy',
      positionTradingStrategyDesc: 'Long-term approach with positions held for months',
      entryRules: 'Entry Rules',
      exitRules: 'Exit Rules',
      scalpingEntryRules: '- RSI between 30-70\\n- High volume (>200k)\\n- Price distance from average',
      scalpingExitRules: '- Stop loss at 0.1%\\n- Take profit at 0.3%\\n- Exit if RSI exceeds 80 or drops below 20',
      dayTradingEntryRules: '- Moving average crossover\\n- Price channel breakout\\n- Significant news',
      dayTradingExitRules: '- Stop loss at 2%\\n- Take profit at 5%\\n- Close before end of day',
      swingTradingEntryRules: '- Trend confirmation\\n- Support/resistance levels\\n- Aligned technical indicators',
      swingTradingExitRules: '- Stop loss at 5%\\n- Take profit at 15%\\n- Trend following',
      positionTradingEntryRules: '- Solid fundamental analysis\\n- Long-term trend\\n- Macroeconomic alignment',
      positionTradingExitRules: '- Stop loss at 10%\n- Take profit at 30%\n- Fundamental trend change',
      hideDiscussions: 'Hide Discussions',
      hideInsights: 'Hide Insights',
      tradingStrategies: 'Trading Strategies',
      euroUsdAnalysis: 'EUR/USD Analysis',
      euroUsdAnalysisDesc: 'EUR/USD pair appears to be forming a bullish continuation pattern in the short-term.',
      goldTrendPrediction: 'Gold Trend Prediction',
      goldTrendPredictionDesc: 'Gold is expected to continue climbing due to increasing geopolitical tensions.',
      oilMarketUpdate: 'Oil Market Update',
      oilMarketUpdateDesc: 'Crude oil inventories declined this week, supporting prices.',
      techStockWatch: 'Tech Stock Watch',
      techStockWatchDesc: 'Tech stocks showing signs of recovery after recent correction.',
      postedBy: 'Posted by',
      userTraderPro: 'TraderPro',
      userMarketGuru: 'MarketGuru',
      userOilExpert: 'OilExpert',
      userTechTrader: 'TechTrader',
      threeHoursAgo: '3 hours ago',
      fourHoursAgo: '4 hours ago',
      sixHoursAgo: '6 hours ago',
      eightHoursAgo: '8 hours ago',
      weeklyMarketOutlook: 'Weekly Market Outlook',
      weeklyMarketOutlookDesc: 'In-depth analysis of dominant trends and upcoming opportunities.',
      riskManagementTips: 'Risk Management Tips',
      riskManagementTipsDesc: 'Best practices for protecting your capital in volatile markets.',
      forexFundamentals: 'Forex Fundamentals',
      forexFundamentalsDesc: 'Understanding economic factors that influence currency pairs.',
      stockValuationGuide: 'Stock Valuation Guide',
      stockValuationGuideDesc: 'Methods for evaluating whether a stock is overvalued or undervalued.',
      by: 'By',
      expertAnalyst: 'ExpertAnalyst',
      expertRiskManager: 'ExpertRiskManager',
      expertForexTrader: 'ExpertForexTrader',
      expertValueInvestor: 'ExpertValueInvestor',
      updatedToday: 'updated today',
      updatedYesterday: 'updated yesterday',
      updatedTwoDaysAgo: 'updated 2 days ago',
      updatedThreeDaysAgo: 'updated 3 days ago',
      viewDiscussion: 'View Discussion',
      readMore: 'Read More',
      tradingStrategiesDesc: 'Share and discover proven trading strategies',
      marketDiscussions: 'Market Discussions',
      marketDiscussionsDesc: 'Discuss market trends with other traders',
      expertInsights: 'Expert Insights',
      expertInsightsDesc: 'Access expert trading analysis',
      activeDiscussions: 'Active Discussions',
      discussionTopic1: 'Day trading strategy for beginners',
      discussionTopic1Desc: 'Browse best practices to start trading',
      discussionTopic2: 'EUR/USD technical analysis',
      discussionTopic2Desc: 'Discussion on key support and resistance levels',
      discussionTopic3: 'Risk management in trading',
      discussionTopic3Desc: 'How to protect your capital with appropriate stops',
      joinCommunity: 'Join Community',
      asset: 'Asset',
      targetPrice: 'Target Price',
      timeframe: 'Timeframe',
      aiBuySignal: 'RSI bullish divergence',
      aiBuyTechnicalAnalysis: 'The Relative Strength Index shows a bullish divergence pattern with price making lower lows while RSI makes higher lows, indicating potential reversal to the upside.',
      aiSellSignal: 'Overbought conditions',
      aiSellTechnicalAnalysis: 'Price is trading above the upper Bollinger Band with RSI above 70, indicating overbought conditions and potential for pullback.',
      aiBuySignal2: 'Support level holding',
      aiBuyTechnicalAnalysis2: 'Price has found strong support at the 78.00 level with increasing volume on bounce, suggesting institutional accumulation.',
      newsHub: 'News Hub',
      newsHubDesc: 'Stay informed of the latest financial news, market trends and economic events in real-time.',
      communityZone: 'Community Zone',
      communityZoneDesc: 'Share your strategies, discuss with other traders and collaborate in our active community of professionals.',
      tradingMasterclass: 'Trading Masterclass',
      tradingMasterclassDesc: 'Exclusive training courses delivered by professional traders to improve your skills and profitability.',
      beginnerCourse: 'Beginner Course',
      beginnerCourseDesc: 'Learn the basics of trading and market analysis',
      advancedCourse: 'Advanced Course',
      advancedCourseDesc: 'Advanced trading techniques and in-depth technical analysis',
      expertCourse: 'Expert Course',
      expertCourseDesc: 'Quantitative analysis and advanced portfolio management',
      specializedCourse: 'Specialized Course',
      specializedCourseDesc: 'Trading in forex, options, and cryptocurrency markets',
      beginnerLevel: 'Beginner',
      intermediateLevel: 'Intermediate',
      advancedLevel: 'Advanced',
      expertLevel: 'Expert',
      courseDetails: 'Course Details',
      topicsCovered: 'Topics Covered',
      enrollNow: 'Enroll Now',
      enrollSuccess: 'Successfully enrolled in the course!',
      hideMasterclass: 'Hide Masterclass',
      lessons: 'Lessons',
      availableCourses: 'Available Courses',
      duration: 'Duration',
      level: 'Level',
      introToTrading: 'Introduction to Trading',
      chartPatterns: 'Chart Patterns',
      riskBasics: 'Risk Management Basics',
      technicalAnalysis: 'Technical Analysis',
      algorithmicTrading: 'Algorithmic Trading',
      portfolioManagement: 'Portfolio Management',
      quantitativeAnalysis: 'Quantitative Analysis',
      riskManagement: 'Risk Management',
      momentumTrading: 'Momentum Trading',
      forexTrading: 'Forex Trading',
      optionsStrategy: 'Options Strategy',
      cryptoMarkets: 'Crypto Markets',
      tradingChallenges: 'Trading Challenges',
      tradingChallengesDesc: 'Take on trading challenges to prove your skills and earn funds to trade with real money.',
      takeChallenge: 'Take Challenge',
      learnMore: 'Learn More',
      technicalAnalysisControls: 'Technical Analysis Controls',
      indicatorType: 'Indicator Type',
      period: 'Period',
      none: 'None',
      simpleMovingAverage: 'Simple Moving Average',
      exponentialMovingAverage: 'Exponential Moving Average',
      movingAverageConvergenceDivergence: 'Moving Average Convergence Divergence',
      stochasticOscillator: 'Stochastic Oscillator',
      williamsR: 'Williams %R',
      smaExplanation: 'Simple Moving Average (SMA) smooths price data by creating a constantly updated average price over a specific time period, helping to identify trend direction and potential support/resistance levels.',
      emaExplanation: 'Exponential Moving Average (EMA) gives more weight to recent prices, making it more responsive to new information compared to SMA, useful for identifying trend changes more quickly.',
      rsiExplanation: 'Relative Strength Index (RSI) measures the speed and change of price movements, ranging from 0 to 100. Values above 70 indicate overbought conditions, while values below 30 indicate oversold conditions.',
      bollingerExplanation: 'Bollinger Bands consist of a middle SMA band and two outer bands that are typically 2 standard deviations away from the SMA. They help identify periods of high or low volatility and potential reversal points.',
      macdExplanation: 'Moving Average Convergence Divergence (MACD) shows the relationship between two EMAs of different periods. It consists of the MACD line, signal line, and histogram, useful for identifying trend changes and momentum shifts.',
      stochasticExplanation: 'Stochastic Oscillator compares a security\'s closing price to its price range over a given time period. It ranges from 0 to 100 and helps identify overbought (above 80) and oversold (below 20) conditions.',
      williamsRExplanation: 'Williams %R is a momentum indicator similar to the Stochastic Oscillator, but inverted. It ranges from -100 to 0, where values above -20 indicate overbought conditions and below -80 indicate oversold conditions.',
      generalExplanation: 'Technical indicators help traders make informed decisions by analyzing price movements, trends, and market sentiment. Use multiple indicators together for better accuracy.',
      showBollingerBands: 'Show Bollinger Bands',
      showRSI: 'Show RSI',
      showMACD: 'Show MACD',
      showStochastic: 'Show Stochastic',
      showWilliamsR: 'Show Williams %R',
      price: 'Price',

      readyToTransformTrading: 'Ready to transform your trading?',
      joinTradersAlreadyUsing: 'Join thousands of traders who already use TradeSense AI',
      createFreeAccount: 'Create Free Account',
      getStartedNow: 'Get Started Now',
      landingProductPlatform: 'The intelligent prop trading platform for ambitious traders',
      quickLinks: 'Quick Links',
      about: 'About',
      helpCenter: 'Help Center',
      documentation: 'Documentation',
      api: 'API',
      support: 'Support',
      allRightsReserved: 'All rights reserved.',
      tradingDashboard: 'Trading Dashboard',
      stockPerformance: 'Stock Performance',
      challengeBalance: 'Challenge Balance',
      selectedAsset: 'Selected Asset',
      currentPrice: 'Current Price',
      lastUpdated: 'Last Updated',
      priceChart: 'Price Chart',
      selectAsset: 'Select an asset',
      buy: 'Buy',
      sell: 'Sell',
      hold: 'Hold',
      realTimeAISignals: 'Real-Time AI Signals',
      reason: 'Reason',
      signalsGeneratedByAI: 'Signals are generated by our AI based on technical analysis and predictive models',
      signalDetails: 'Signal Details',
      confidence: 'Confidence',
      timeFrame: 'Time Frame',
      targetPrice: 'Target Price',
      stopLoss: 'Stop Loss',
      indicatorsUsed: 'Indicators Used',
      close: 'Close',
      goToTrainingCourses: 'Go to Training Courses',
      tradingStats: 'Trading Statistics',
      openPositions: 'Open Positions',
      profitLoss: 'Profit/Loss',
      successRate: 'Success Rate',
      volatility: 'Volatility',
      medium: 'Medium',
      marketNews: 'Latest Market News',
      iamUpQuarterly: 'IAM rises 2.5% after quarterly results',
      hoursAgo: '{hours} hours ago',
      purchaseSuccess: 'Purchase of {asset} completed successfully!',
      purchaseError: 'Error during purchase',
      purchaseRetry: 'Error during purchase. Please try again.',
      saleSuccess: 'Sale of {asset} completed successfully!',
      saleError: 'Error during sale',
      saleRetry: 'Error during sale. Please try again.',
      fetchPriceError: 'Error retrieving price',
      traderLeaderboard: 'Trader Leaderboard',
      top10TradersByProfitPercent: 'Top 10 traders by profit percentage',
      rank: 'Rank',
      profitPercent: 'Profit (%)',
      totalProfitDollar: 'Total Profit ($)',
      transactions: 'Transactions',
      funded: 'Funded',
      active: 'Active',
      failed: 'Failed',
      rankingMethodology: 'Ranking Methodology',
      rankingExplanation: 'Traders are ranked according to their net profit percentage calculated as follows: (Final Balance - Initial Balance) / Initial Balance × 100. Only completed challenges are eligible for ranking.',
      fetchLeaderboardError: 'Error fetching leaderboard data',
      adminPanel: 'Admin Panel',
      userManagement: 'User management and their statuses',
      userId: 'ID',
      username: 'Username',
      email: 'Email',
      challengeId: 'Challenge ID',
      challengeStatus: 'Challenge Status',
      currentBalance: 'Current Balance',
      initialBalance: 'Initial Balance',
      actions: 'Actions',
      modify: 'Modify',
      updateChallengeStatus: 'Update Challenge Status',
      user: 'User',
      update: 'Update',
      loadingUsers: 'Loading users...',
      fetchUsersError: 'Error loading users',
      updateStatusError: 'Error updating status',
      noChallenge: 'None',
      nA: 'N/A',
      chooseYourPlan: 'Choose Your Plan',
      accessAdvancedFeatures: 'Access advanced features to optimize your trading',
      perMonth: 'per month',
      popular: 'POPULAR',
      chooseStarter: 'Choose Starter',
      choosePro: 'Choose Pro',
      chooseElite: 'Choose Elite',
      processingPayment: 'Processing payment...',
      paymentSuccess: 'Payment successful!',
      payment: 'Payment',
      paymentProcessing: 'Processing your payment...',
      pleaseWaitPaymentProcessing: 'Please wait while we process your payment of {price} {currency}.',
      paymentSuccessMessage: 'Thank you for your payment of {price} {currency}.<br />Your {plan} subscription is now active.',
      paymentInfo: 'Payment of {price} {currency} for the {plan} plan',
      cardNumber: 'Card Number',
      expiryDate: 'Expiry Date',
      cvv: 'CVV',
      cardHolderName: 'Card Holder Name',
      saveForFuturePayments: 'Save this information for future payments',
      cancel: 'Cancel',
      payAmount: 'Pay {price} {currency}',
      whyChooseTradeSense: 'Why choose TradeSense AI?',
      advancedAI: 'Advanced Artificial Intelligence',
      advancedAIExplanation: 'Our AI algorithms analyze millions of data in real-time to provide you with the best trading signals.',
      completePlatform: 'Complete Platform',
      completePlatformExplanation: 'All-in-one: advanced charts, AI signals, portfolio management, and professional trader community.',
      localSupport: 'Local Support',
      localSupportExplanation: 'Customer service available in French and Arabic, with expertise in the Moroccan and international markets.',
      starterFeatures: ['Access to basic charts', '5 AI signals per day', 'Email support', '1 trading challenge', 'Limited history'],
      proFeatures: ['All Starter benefits', 'Unlimited AI signals', 'Priority support', '5 trading challenges', 'Advanced technical analysis', 'Monthly webinars'],
      eliteFeatures: ['All Pro benefits', 'Early access to new features', 'Personalized coaching session', 'VIP community access', 'Real-time AI signals', 'Exclusive weekly analyses', '24/7 support'],
      paymentFailure: 'Payment failed. Please check your card information.',
      tradeSenseAuth: 'TradeSense AI - Authentication',
      confirmPassword: 'Confirm Password',
      passwordsDontMatch: 'Passwords do not match',
      registrationSuccess: 'Registration successful! You can now log in.',
      registrationError: 'Error during registration',
      loginRequiredFields: 'Please fill in all required fields',
      loginSuccess: 'Login successful!',
      loginError: 'Error during login',
      networkError: 'Network error. Please try again.',
      checkingConnection: 'Checking connection...',
      connectionTroubleShoot: 'Please make sure the backend server is running on port 5000.',
      connectionTroubleshootSteps: 'Troubleshooting steps: Make sure the backend server is running on port 5000, check firewall settings, and verify network connectivity.',
      requiredFields: 'Please fill in all required fields',
      confirmPurchase: 'Confirm Purchase',
      confirmPurchaseMessage: 'Are you sure you want to purchase the {plan} challenge?'
    },
    // Add more translations as needed
    ar: {
      // Arabic translations
      dashboard: 'اللوحة الرئيسية',
      leaderboard: 'التصنيف',
      pricing: 'التسعير',
      admin: 'الإدارة',
      home: 'الرئيسية',
      login: 'تسجيل الدخول',
      register: 'التسجيل',
      logout: 'تسجيل الخروج',
      darkMode: 'الوضع الليلي',
      lightMode: 'الوضع النهاري',
      language: 'اللغة',
      french: 'الفرنسية',
      english: 'الإنجليزية',
      arabic: 'العربية',
      productVision: 'رؤيتنا للمنتج',
      productVisionDescription: 'منصة كاملة تجمع بين الذكاء الاصطناعي وتحليل السوق ومجتمع المتداولين',
      advancedAIAssistance: 'مساعدة ذكية متقدمة',
      advancedAIAssistanceDesc: 'يحلل الذكاء الاصطناعي الخاص بنا الأسواق في الوقت الفعلي لتزويدك بإشارات التداول الدقيقة وتحليلات فنية معمقة.',
      preciseTradingSignals: 'إشارات التداول الدقيقة',
      latestFinancialNews: 'أحدث الأخبار المالية',
      iamUpQuarterly: 'أظهرت IAM تقدماً بنسبة 5٪ في الربع الأخير',
      ago: 'منذ',
      close: 'إغلاق',
      goToDashboard: 'الانتقال إلى لوحة التحكم',
      goToTrainingCourses: 'الذهاب إلى الدورات التدريبية',
      videos: 'فيديوهات',
      courseContent: 'محتوى الدورة',
      learningMaterials: 'مواد التعلم',
      courseProgress: 'التقدم',
      progressOverview: 'نظرة عامة على التقدم',
      courseProgressDescription: 'أكمل الوحدات المختلفة للتقدم في الدورة.',
      markAsComplete: 'وضع علامة على أنها مكتملة',
      congratulations: 'تهانينا!',
      courseCompletedSuccessfully: 'لقد أكملت الدورة بنجاح!',
      courseCertificateInfo: 'يمكنك الآن تنزيل شهادة الإتمام الخاصة بك.',
      downloadCertificate: 'تنزيل الشهادة',
      courseNotFound: 'الدورة غير موجودة',
      download: 'تنزيل',
      hideCommunity: 'إخفاء المجتمع',
      hideStrategies: 'إخفاء الاستراتيجيات',
      communityFeatures: 'مزايا المجتمع',
      scalpingStrategy: 'استراتيجية التسلق',
      scalpingStrategyDesc: 'استراتيجية قصيرة جدًا تهدف إلى تحقيق أرباح صغيرة في العديد من المعاملات',
      dayTradingStrategy: 'استراتيجية التداول اليومي',
      dayTradingStrategyDesc: 'شراء وبيع الأسهم في نفس اليوم دون مراكز ليلية',
      swingTradingStrategy: 'استراتيجية التداول بالاهتزاز',
      swingTradingStrategyDesc: 'احتفاظ بالPositions لعدة أيام إلى عدة أسابيع',
      positionTradingStrategy: 'استراتيجية تداول المراكز',
      positionTradingStrategyDesc: 'نهج طويل الأجل مع احتفاظ بالPositions لأشهر',
      entryRules: 'قواعد الدخول',
      exitRules: 'قواعد الخروج',
      scalpingEntryRules: '- RSI بين 30-70\\n- حجم عالي (>200k)\\n- بعد السعر عن المتوسط',
      scalpingExitRules: '- أمر وقف الخسارة عند 0.1%\\n- أمر جني الأرباح عند 0.3%\\n- الخروج إذا تجاوز RSI 80 أو انخفض تحت 20',
      dayTradingEntryRules: '- تقاطع متوسطات متحركة\\n- اختراق قناة السعر\\n- أخبار هامة',
      dayTradingExitRules: '- أمر وقف الخسارة عند 2%\\n- أمر جني الأرباح عند 5%\\n- الإغلاق قبل نهاية اليوم',
      swingTradingEntryRules: '- تأكيد الاتجاه\\n- مستويات الدعم/المقاومة\\n- مؤشرات فنية متوافقة',
      swingTradingExitRules: '- أمر وقف الخسارة عند 5%\\n- أمر جني الأرباح عند 15%\\n- تتبع الاتجاه',
      positionTradingEntryRules: '- تحليل أساسي سليم\\n- اتجاه طويل الأجل\\n- توافق كلي',
      positionTradingExitRules: '- أمر وقف الخسارة عند 10%\n- أمر جني الأرباح عند 30%\n- تغيير في الاتجاه الأساسي',
      hideDiscussions: 'إخفاء المناقشات',
      hideInsights: 'إخفاء الأفكار',
      tradingStrategies: 'استراتيجيات التداول',
      euroUsdAnalysis: 'تحليل EUR/USD',
      euroUsdAnalysisDesc: 'يبدو أن زوج EUR/USD يشكل نمطًا تصاعديًا في المدى القصير.',
      goldTrendPrediction: 'توقع اتجاه الذهب',
      goldTrendPredictionDesc: 'من المتوقع أن يستمر الذهب في الارتفاع بسبب التوترات الجيوسياسية المتزايدة.',
      oilMarketUpdate: 'تحديث سوق النفط',
      oilMarketUpdateDesc: 'انخفضت مخزونات النفط الخام هذا الأسبوع، مما يدعم الأسعار.',
      techStockWatch: 'مراقبة أسهم التكنولوجيا',
      techStockWatchDesc: 'تظهر أسهم التكنولوجيا علامات على التعافي بعد التصحيح الأخير.',
      postedBy: 'منشور بواسطة',
      userTraderPro: 'TraderPro',
      userMarketGuru: 'MarketGuru',
      userOilExpert: 'OilExpert',
      userTechTrader: 'TechTrader',
      threeHoursAgo: 'قبل 3 ساعات',
      fourHoursAgo: 'قبل 4 ساعات',
      sixHoursAgo: 'قبل 6 ساعات',
      eightHoursAgo: 'قبل 8 ساعات',
      weeklyMarketOutlook: 'نظرة السوق الأسبوعية',
      weeklyMarketOutlookDesc: 'تحليل معمق للاتجاهات السائدة والفرص القادمة.',
      riskManagementTips: 'نصائح إدارة المخاطر',
      riskManagementTipsDesc: 'أفضل الممارسات لحماية رأس مالك في الأسواق المتقلبة.',
      forexFundamentals: 'أساسيات الفوركس',
      forexFundamentalsDesc: 'فهم العوامل الاقتصادية التي تؤثر على أزواج العملات.',
      stockValuationGuide: 'دليل تقييم الأسهم',
      stockValuationGuideDesc: 'طرق لتقييم ما إذا كانت الأسهم مُبالغ في تقديرها أو دون تقديرها.',
      by: 'بواسطة',
      expertAnalyst: 'ExpertAnalyst',
      expertRiskManager: 'ExpertRiskManager',
      expertForexTrader: 'ExpertForexTrader',
      expertValueInvestor: 'ExpertValueInvestor',
      updatedToday: 'تم التحديث اليوم',
      updatedYesterday: 'تم التحديث أمس',
      updatedTwoDaysAgo: 'تم التحديث قبل يومين',
      updatedThreeDaysAgo: 'تم التحديث قبل 3 أيام',
      viewDiscussion: 'عرض المناقشة',
      readMore: 'اقرأ المزيد',
      tradingStrategiesDesc: 'شارك واكتشف استراتيجيات التداول المثبتة',
      marketDiscussions: 'مناقشات السوق',
      marketDiscussionsDesc: 'ناقش اتجاهات السوق مع متداولين آخرين',
      expertInsights: 'تحليلات الخبراء',
      expertInsightsDesc: 'الوصول إلى تحليلات التداول من قبل الخبراء',
      activeDiscussions: 'المناقشات النشطة',
      discussionTopic1: 'استراتيجية التداول اليومي للمبتدئين',
      discussionTopic1Desc: 'تصفح أفضل الممارسات لبدء التداول',
      discussionTopic2: 'التحليل الفني لـ EUR/USD',
      discussionTopic2Desc: 'مناقشة مستويات الدعم والمقاومة الرئيسية',
      discussionTopic3: 'إدارة المخاطر في التداول',
      discussionTopic3Desc: 'كيفية حماية رأس مالك باستخدام أوامر الإيقاف المناسبة',
      joinCommunity: 'الانضمام إلى المجتمع',
      asset: 'الأصل',
      targetPrice: 'السعر المستهدف',
      timeframe: 'الإطار الزمني',
      close: 'إغلاق',
      aiBuySignal: 'انحراف صعودي في RSI',
      aiBuyTechnicalAnalysis: 'يُظهر مؤشر القوة النسبية نمط انحراف صعودي حيث يُسجل السعر قيعانًا أقل بينما يُسجل RSI قيعانًا أعلى، مما يشير إلى احتمال عكس الاتجاه نحو الأعلى.',
      aiSellSignal: 'ظروف التشبع الشرائي',
      aiSellTechnicalAnalysis: 'يُتداول السعر أعلى من حزمة بولينجر العلوية مع RSI أكثر من 70، مما يدل على ظروف التشبع الشرائي وإمكانية التراجع.',
      aiBuySignal2: 'التمسك بمستوى الدعم',
      aiBuyTechnicalAnalysis2: 'لقد وجد السعر دعمًا قويًا عند مستوى 78.00 مع زيادة في الحجم عند الارتداد، مما يشير إلى تراكم المؤسسات.',
      newsHub: 'مركز الأخبار',
      newsHubDesc: 'ابق على اطلاع دائم بأحدث الأخبار المالية واتجاهات السوق والأحداث الاقتصادية في الوقت الفعلي.',
      communityZone: 'منطقة المجتمع',
      communityZoneDesc: 'شارك استراتيجياتك وناقش مع متداولين آخرين وتعاون في مجتمعنا النشط للمحترفين.',
      tradingMasterclass: 'دروس التداول المتخصصة',
      tradingMasterclassDesc: 'دورات تدريبية حصرية يقدمها متداولون محترفون لتحسين مهاراتك وربحك.',
      beginnerCourse: 'دورة المبتدئين',
      beginnerCourseDesc: 'تعلم أساسيات التداول وتحليل السوق',
      advancedCourse: 'دورة متقدمة',
      advancedCourseDesc: 'تقنيات تداول متقدمة وتحليل فني عميق',
      expertCourse: 'دورة الخبراء',
      expertCourseDesc: 'تحليل كمي وإدارة محفظة متقدمة',
      specializedCourse: 'دورة متخصصة',
      specializedCourseDesc: 'التجارة في الفوركس والخيارات والعملات المشفرة',
      beginnerLevel: 'مبتدئ',
      intermediateLevel: 'متوسط',
      advancedLevel: 'متقدم',
      expertLevel: 'خبير',
      courseDetails: 'تفاصيل الدورة',
      topicsCovered: 'المواضيع المغطاة',
      enrollNow: 'التسجيل الآن',
      enrollSuccess: 'تم التسجيل في الدورة بنجاح!',
      hideMasterclass: 'إخفاء دروس التداول',
      lessons: 'دروس',
      availableCourses: 'الدورات المتوفرة',
      duration: 'المدة',
      level: 'المستوى',
      introToTrading: 'مقدمة للتداول',
      chartPatterns: 'أنماط المخططات',
      riskBasics: 'أساسيات إدارة المخاطر',
      technicalAnalysis: 'التحليل الفني',
      algorithmicTrading: 'التداول الخوارزمي',
      portfolioManagement: 'إدارة المحفظة',
      quantitativeAnalysis: 'التحليل الكمي',
      riskManagement: 'إدارة المخاطر',
      momentumTrading: 'التداول بالزخم',
      forexTrading: 'تداول الفوركس',
      optionsStrategy: 'استراتيجية الخيارات',
      cryptoMarkets: 'أسواق العملات المشفرة',
      tradingChallenges: 'تحديات التداول',
      tradingChallengesDesc: 'واجه تحديات التداول لإثبات مهاراتك وكسب الأموال للتداول باستخدام أموال حقيقية.',
      takeChallenge: 'واجه التحدي',
      learnMore: 'تعرف على المزيد',
      technicalAnalysisControls: 'عناصر تحكم التحليل الفني',
      indicatorType: 'نوع المؤشر',
      period: 'الفترة',
      none: 'لا شيء',
      simpleMovingAverage: 'المتوسط المتحرك البسيط',
      exponentialMovingAverage: 'المتوسط المتحرك الأسي',
      movingAverageConvergenceDivergence: 'تقارب/تباعد المتوسطات المتحركة',
      stochasticOscillator: 'مؤشر ستوكاستيك',
      williamsR: 'ويليامز %R',
      smaExplanation: 'المتوسط المتحرك البسيط (SMA) يُنعم بيانات السعر من خلال إنشاء متوسط سعر مُحدّث باستمرار على مدى فترة زمنية محددة، مما يساعد على تحديد اتجاه الاتجاه ومستويات الدعم/المقاومة المحتملة.',
      emaExplanation: 'المتوسط المتحرك الأسي (EMA) يعطي وزناً أكبر للأثمان الحديثة، مما يجعله أكثر استجابة للمعلومات الجديدة مقارنة بـ SMA، وهو مفيد لتحديد تغيرات الاتجاه بشكل أسرع.',
      rsiExplanation: 'مؤشر القوة النسبية (RSI) يقيس سرعة وتغير حركات الأسعار، ويتراوح من 0 إلى 100. تشير القيم فوق 70 إلى ظروف التشبع الشرائي، بينما تشير القيم أدناه 30 إلى ظروف التشبع البيعي.',
      bollingerExplanation: 'تتكون نطاقات بولينجر من نطاق وسطي SMA ونطاقين خارجيين يكونان عادة على بعد انحرافين معياريين من SMA. تساعد في تحديد فترات التقلبات العالية أو المنخفضة ونقاط التحوّل المحتملة.',
      macdExplanation: 'يتقارب/يبتعد المتوسطات المتحركة (MACD) يُظهر العلاقة بين متوسطين أسيين مختلفين في الفترات. يتكون من خط MACD وخط الإشارة وهيستوغرام، وهو مفيد لتحديد تغيرات الاتجاه وتحولات الزخم.',
      stochasticExplanation: 'يقارن المؤشر ستوكاستيك سعر إغلاق الورقة المالية بטווח أسعارها على مدى فترة زمنية معينة. يتراوح من 0 إلى 100 ويساعد في تحديد ظروف التشبع الشرائي (أعلى من 80) والتشبع البيعي (أدنى من 20).',
      williamsRExplanation: 'ويليامز %R هو مؤشر زخم مشابه لمؤشر ستوكاستيك، لكنه معكوس. يتراوح من -100 إلى 0، حيث تشير القيم أعلى من -20 إلى ظروف التشبع الشرائي وأدنى من -80 إلى ظروف التشبع البيعي.',
      generalExplanation: 'تساعد المؤشرات الفنية المتداولين على اتخاذ قرارات مستنيرة من خلال تحليل حركات الأسعار والاتجاهات ومشاعر السوق. استخدم عدة مؤشرات معًا للحصول على دقة أفضل.',
      showBollingerBands: 'إظهار نطاقات بولينجر',
      showRSI: 'إظهار مؤشر القوة النسبية',
      showMACD: 'إظهار MACD',
      showStochastic: 'إظهار ستوكاستيك',
      showWilliamsR: 'إظهار ويليامز %R',
      price: 'السعر',

      readyToTransformTrading: 'هل أنت مستعد لتحويل تداولك؟',
      joinTradersAlreadyUsing: 'انضم إلى الآلاف من المتداولين الذين يستخدمون بالفعل TradeSense AI',
      createFreeAccount: 'إنشاء حساب مجاني',
      getStartedNow: 'ابدأ الآن',
      landingProductPlatform: 'منصة التداول الذكية لتجار الطموحين',
      quickLinks: 'روابط سريعة',
      about: 'حول',
      helpCenter: 'مركز المساعدة',
      documentation: 'التوثيق',
      api: 'API',
      support: 'الدعم',
      allRightsReserved: 'جميع الحقوق محفوظة.',
      tradingDashboard: 'لوحة التحكم في التداول',
      stockPerformance: 'أداء الأسهم',
      challengeBalance: 'رصيد التحدي',
      selectedAsset: 'الأصل المحدد',
      currentPrice: 'السعر الحالي',
      lastUpdated: 'آخر تحديث',
      priceChart: 'مخطط السعر',
      selectAsset: 'اختر أصلاً',
      buy: 'شراء',
      sell: 'بيع',
      hold: 'احتفاظ',
      realTimeAISignals: 'إشارات الذكاء الاصطناعي في الوقت الفعلي',
      reason: 'السبب',
      signalsGeneratedByAI: 'يتم إنشاء الإشارات بواسطة ذكائنا الاصطناعي بناءً على التحليل الفني والنماذج التنبؤية',
      signalDetails: 'تفاصيل الإشارة',
      confidence: 'مستوى الثقة',
      timeFrame: 'الإطار الزمني',
      targetPrice: 'السعر المستهدف',
      stopLoss: 'وقف الخسارة',
      indicatorsUsed: 'المؤشرات المستخدمة',
      tradingStats: 'إحصائيات التداول',
      openPositions: 'المراكز المفتوحة',
      profitLoss: 'الربح/الخسارة',
      successRate: 'نسبة النجاح',
      volatility: 'تقلب السوق',
      medium: 'متوسط',
      marketNews: 'آخر أخبار السوق',
      iamUpQuarterly: 'ارتفع سهم IAM بنسبة 2.5٪ بعد النتائج الفصلية',
      hoursAgo: 'قبل {hours} ساعات',
      purchaseSuccess: 'اكتمل شراء {asset} بنجاح!',
      purchaseError: 'خطأ أثناء الشراء',
      purchaseRetry: 'خطأ أثناء الشراء. يرجى المحاولة مرة أخرى.',
      saleSuccess: 'اكتمل بيع {asset} بنجاح!',
      saleError: 'خطأ أثناء البيع',
      saleRetry: 'خطأ أثناء البيع. يرجى المحاولة مرة أخرى.',
      fetchPriceError: 'خطأ أثناء استرداد السعر',
      traderLeaderboard: 'متصدرو المتداولين',
      top10TradersByProfitPercent: 'أفضل 10 متداولين حسب نسبة الربح',
      rank: 'المرتبة',
      profitPercent: 'الربح (%)',
      totalProfitDollar: 'إجمالي الربح ($)',
      transactions: 'المعاملات',
      funded: 'ممول',
      active: 'نشط',
      failed: 'فشل',
      rankingMethodology: 'منهجية التصنيف',
      rankingExplanation: 'يتم تصنيف المتداولين وفقًا لنسبة ربحهم الصافية المحسوبة على النحو التالي: (الرصيد النهائي - الرصيد الأولي) / الرصيد الأولي × 100. يحق فقط للتحديات المكتملة التصنيف.',
      fetchLeaderboardError: 'خطأ في جلب بيانات المتصدرين',
      adminPanel: 'لوحة الإدارة',
      userManagement: 'إدارة المستخدمين وstatuses الخاصة بهم',
      userId: 'المعرف',
      username: 'اسم المستخدم',
      email: 'البريد الإلكتروني',
      challengeId: 'معرف التحدي',
      challengeStatus: 'حالة التحدي',
      currentBalance: 'الرصيد الحالي',
      initialBalance: 'الرصيد الأولي',
      actions: 'الإجراءات',
      modify: 'تعديل',
      updateChallengeStatus: 'تحديث حالة التحدي',
      user: 'المستخدم',
      status: 'الحالة',
      update: 'تحديث',
      loadingUsers: 'جارٍ تحميل المستخدمين...',
      fetchUsersError: 'خطأ في تحميل المستخدمين',
      updateStatusError: 'خطأ في تحديث الحالة',
      noChallenge: 'لا شيء',
      nA: 'غير متاح',
      chooseYourPlan: 'اختر خطتك',
      accessAdvancedFeatures: 'الوصول إلى ميزات متقدمة لتحسين تداولك',
      perMonth: 'شهريًا',
      popular: 'شائع',
      chooseStarter: 'اختر البدء',
      choosePro: 'اختر الاحترافي',
      chooseElite: 'اختر النخبة',
      processingPayment: 'جاري معالجة الدفع...',
      paymentSuccess: 'تم الدفع بنجاح!',
      payment: 'الدفع',
      paymentProcessing: 'جاري معالجة دفعتك...',
      pleaseWaitPaymentProcessing: 'الرجاء الانتظار بينما نعالج دفعتك البالغة {price} {currency}.',
      paymentSuccessMessage: 'شكرًا لدفعتك البالغة {price} {currency}.<br />اشتراكك في {plan} نشط الآن.',
      paymentInfo: 'دفعة بقيمة {price} {currency} لخطة {plan}',
      cardNumber: 'رقم البطاقة',
      expiryDate: 'تاريخ الانتهاء',
      cvv: 'رمز الأمان',
      cardHolderName: 'اسم حامل البطاقة',
      saveForFuturePayments: 'احفظ هذه المعلومات للدفعات المستقبلية',
      payAmount: 'ادفع {price} {currency}',
      whyChooseTradeSense: 'لماذا تختار TradeSense AI؟',
      advancedAI: 'الذكاء الاصطناعي المتقدم',
      advancedAIExplanation: 'تحلل خوارزمياتنا الذكية ملايين البيانات في الوقت الفعلي لتزويدك بإشارات التداول الأفضل.',
      completePlatform: 'منصة متكاملة',
      completePlatformExplanation: 'كل شيء في مكان واحد: مخططات متقدمة، إشارات ذكية، إدارة المحافظ، ومجتمع المتداولين المحترفين.',
      localSupport: 'دعم محلي',
      localSupportExplanation: 'خدمة العملاء متاحة باللغتين الفرنسية والعربية، مع خبرة في السوق المغربي والدولي.',
      starterFeatures: ['الوصول إلى المخططات الأساسية', '5 إشارات ذكية يوميًا', 'دعم عبر البريد الإلكتروني', 'تحدي تداول واحد', 'سجل محدود'],
      proFeatures: ['جميع مزايا البدء', 'إشارات ذكية غير محدودة', 'دعم أولوي', '5 تحديات تداول', 'تحليل فني متقدم', 'ورش عمل شهرية'],
      eliteFeatures: ['جميع مزايا الاحترافي', 'الوصول المبكر للميزات الجديدة', 'جلسة تدريب مخصصة', 'وصول إلى مجتمع النخبة', 'إشارات ذكية في الوقت الفعلي', 'تحليلات أسبوعية حصرية', 'دعم 24/7'],
      paymentFailure: 'فشل الدفع. يرجى التحقق من معلومات بطاقتك.',
      tradeSenseAuth: 'TradeSense AI - المصادقة',
      confirmPassword: 'تأكيد كلمة المرور',
      passwordsDontMatch: 'كلمات المرور غير متطابقة',
      registrationSuccess: 'تم التسجيل بنجاح! يمكنك الآن تسجيل الدخول.',
      registrationError: 'خطأ أثناء التسجيل',
      loginRequiredFields: 'الرجاء ملء جميع الحقول المطلوبة',
      loginSuccess: 'تم تسجيل الدخول بنجاح!',
      loginError: 'خطأ أثناء تسجيل الدخول',
      networkError: 'خطأ في الشبكة. يرجى المحاولة مرة أخرى.',
      checkingConnection: 'التحقق من الاتصال...',
      connectionTroubleShoot: 'يرجى التأكد من أن خادم الواجهة الخلفية يعمل على المنفذ 5000.',
      connectionTroubleshootSteps: 'خطوات استكشاف الأخطاء وإصلاحها: تأكد من أن خادم الواجهة الخلفية قيد التشغيل على المنفذ 5000، وتحقق من إعدادات جدار الحماية، وتأكد من اتصال الشبكة.',
      requiredFields: 'الرجاء ملء جميع الحقول المطلوبة',
      confirmPurchase: 'تأكيد الشراء',
      confirmPurchaseMessage: 'هل أنت متأكد أنك تريد شراء تحدي {plan}?'
    }
  };

  // Add more translations as needed
  var value = {
    mode: mode,
    toggleTheme: toggleTheme,
    language: language,
    changeLanguage: changeLanguage,
    updateTranslations: function updateTranslations(newLanguage) {
      return setLanguage(newLanguage);
    },
    t: translations[language] || translations.fr, // Fallback to French
    theme: theme
  };

  return _react2['default'].createElement(
    _muiMaterialStyles.ThemeProvider,
    { theme: theme },
    _react2['default'].createElement(
      AppContext.Provider,
      { value: value },
      children
    )
  );
};

exports.AppProvider = AppProvider;
var useAppContext = function useAppContext() {
  var context = (0, _react.useContext)(AppContext);
  if (!context) {
    throw new Error('useAppContext must be used within an AppProvider');
  }
  return context;
};
exports.useAppContext = useAppContext;
